twig:
    default_path: '%kernel.project_dir%/templates'
# config/packages/twig.yaml // indentation important sinon cela ne fonctionne pas
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        url_images: "/images/"
        url_images_livres: "/images/livres/"